# Site language
lang: en-US

# Site title
title: "Foxware"

# A description of your site for meta tag, search engine results.
description: "Blogs"

# The subpath of your site, e.g. /blog, for generating urls.
baseurl: "/blogs"

# The base hostname & protocol of your site for where absolute urls are needed.
url: "https://foxdocs.github.io/"

# Favicon
favicon: images/favicon.ico

# Google Analytics id, e.g. "UA-NNNNNNNN-N"
google_analytics: ""

# Site navigation - each item must have a title and a url.
navigation:
  - text: Home
    url: /
  - text: About
    url: /about/
  - text: Style Guide
    url: /style-guide/
  - text: Tags
    url: /tags/
  - text: Download
    url: https://github.com/foxdocs/blogs

# The shortname for your Disqus site to enable comments.
disqus: 

# Colors
accent_color: '#2d72d9'

# Site footer
footer:
  content: "&copy; All rights reserved. Theme by [JustGoodThemes](https://www.justgoodthemes.com)."
  has_social: true

# Plugins
plugins:
  - jekyll-paginate

# http://jekyllrb.com/docs/pagination/
paginate: 3
paginate_path: '/page:num/'


# Permalinks
permalink: /:title

# Conversion
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
